### ISSUE TITLE
Output doesn't list server/page name

### ISSUE THREAD

**Issue by rbsec** [dionach/HeadersAnalyzer#1]
The output in the Headers Analyzer tab just lists the headers, it doesn't tell you which server or page they're from. Example output below. Also, that should probably read "Missing security headers" or something; "missing headers found" doesn't really make sense.

[+] Interesting Headers found:
    Header name:server Header value: Apache
[+] Missing headers found:
    Header name:x-frame-options
    Header name:x-content-type-options
    Header name:strict-transport-security
    Header name:content-security-policy
    Header name:x-permitted-cross-domain-policies
[+] Interesting Headers found:
    Header name:server Header value: Apache
[+] Missing headers found:
    Header name:x-frame-options
    Header name:x-content-type-options
    Header name:strict-transport-security
    Header name:content-security-policy
    Header name:x-permitted-cross-domain-policies

**Comment by antoniosanchezc-zz** [comment]
Logs output improved according to the suggestion. New output looks like:

[+] Missing security headers: www.example.com
    Header name:x-frame-options
    Header name:x-content-type-options
    Header name:strict-transport-security
    Header name:content-security-policy
